baseURL = 'https://jaconsta.com/'
languageCode = 'en-us'
title = 'Jaconsta web'
theme = 'ananke'

DefaultContentLanguage = "en"
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Jaconsta"
    description = "ğŸ¦€ | ğŸŸ¨ / ğŸŸ¦Ê¦ | âš› | ğŸ¹ | ğŸ¯| ğŸ"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
# site_logo = "images/gecko_logo.jpg"

[[params.ananke_socials]]
  name = 'linkedin'
  label= 'LinkedIn'
  url= 'https://de.linkedin.com/in/jaconsta'
[[params.ananke_socials]]
  name= 'twitter'
  url= 'https://twitter.com/jaconsta'
  label= 'Jaconsta Twitter'
[[params.ananke_socials]]
  name= 'github'
    url= 'https://github.com/Jaconsta'
    label= 'Jaconsta GitHub Account'
    color= '#ff6800'

